name: pr

on:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: touch test123
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > ./pr_number

      - run: ls -R

      - uses: actions/upload-artifact@v3
        with:
          name: test123-artifact
          path: |
            ./test123
            ./pr_number
