name: privileged

permissions:
  pull-requests: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: [pr]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
      - name: 'Download artifact'
        uses: ./.github/actions/download-workflow-artifact
        with:
          artifact-name: test123-artifact
          save-as: test123-artifact.zip

      - run: unzip test123-artifact.zip

      - run: ls -R

      - name: 'Leave comment on PR with test results'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fs = require('fs');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(fs.readFileSync('./pr_number')),
              body: `Hello world`
            });