name: privileged

on:
  workflow_dispatch:
  workflow_run:
    workflows: [pr]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    # if: toJSON(github.event.workflow_run.pull_requests) != '[]'
    steps:
      - run: echo ${{ toJSON(github.event.workflow_run.pull_requests) }}
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "test123-artifact"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/test123-artifact.zip`, Buffer.from(download.data));

      - run: ls -R

      - run: unzip test123-artifact.zip

      - run: ls -R

      - name: 'Leave comment on PR with test results'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number:  context.payload.workflow_run.pull_requests[0].number,
              body: `Hello world`
            });